### ISSUE TITLE
Messed up obfuscation of nested functions in \() string

### ISSUE THREAD

**Issue by vrujbr** [rockbruno/swiftshield#109]
Nested calls inside string created with \() got messed up.

`log("response up message 📲: \(JSON.parse(paramsString.unobfuscate()).description)")`

got obfuscated to

`AQOw1XCKd0NolwHH89G2DKGX5q1vnJB3("response up message 📲: \(JSON.pxu1lkQRhB9zWzsGEjbArgE0T65KOp21E(JpWJTdblzfsV4VlVMv1moOCdfDBSccFVsString.unobfuAhgCdyj7Z7ZGTjQY4l80RSJVcvwlfapLscription)")`

From conversion map:
log ===> AQOw1XCKd0NolwHH89G2DKGX5q1vnJB3
JSON ===> xu1lkQRhB9zWzsGEjbArgE0T65KOp21E
parse ===> JpWJTdblzfsV4VlVMv1moOCdfDBSccFV
unobfuscate ===> AhgCdyj7Z7ZGTjQY4l80RSJVcvwlfapL

**Comment by rockbruno** [comment]
I think this is the emoji issue: https://github.com/rockbruno/swiftshield/blob/master/SOURCEKITISSUES.md#sourcekit-bugs

The problem is that in your Xcode view the emoji is a single character, but SourceKit treats it as multiple ones (I guess it considers each node in the unicode's grapheme cluster). I never found a solution for this, but I haven't tried much either. I think it can be fixed.

**Comment by vrujbr** [comment]
Ok that makes sense, I guess there is no need to spend time fixing it (there is no *need* to use those emojis..)

**Comment by rockbruno** [comment]
https://developer.apple.com/documentation/swift/unicode/scalar/properties/3081577-isemoji

These didn't used to exist when I first saw this, so I think it's easy to push a fix now :)

**Comment by rockbruno** [comment]
https://github.com/rockbruno/swiftshield/pull/110

**Comment by rockbruno** [comment]
Pushed as 4.0.1 :)
