### ISSUE TITLE
Segmentation fault in ResultProtocol.swift

### ISSUE THREAD

**Issue by nolliekrey** [rockbruno/swiftshield#24]
Hello

While trying to use SwiftShield 3.3.0 against my greater project I saw that the tool had a segmentation fault when it reached the free Pod Result's file ResultProtocol. To confirm I ran it against Result by itself.

```
[user@compy Result (master)]$ pwd
../Pods/Result
[user@compy Result (master)]$ ls
LICENSE		README.md	Result
[user@compy Result (master)]$ ls Result/
Result.swift		ResultProtocol.swift
[user@compy Result (master)]$ swiftshield -project-root . -tag __j
SwiftShield 3.3.0
Manual mode
Using tag: __j
--- Searching for tagged objects ---
--- Checking ResultProtocol.swift ---
Segmentation fault: 11
[user@compy Result (master)]$ 
```

ResultProtocol contains infix operators. Perhaps they lead to the crash?

**Comment by rockbruno** [comment]
Is the Pod folder unlocked? This segmentation fault usually happens because the folders are write-locked. [You can see how to unlock it here](https://github.com/rockbruno/swiftshield/blob/master/USAGE.md)
If that's not the case, can you link the file here? I made some changes to the manual mode, so I could have broke something!

**Comment by nolliekrey** [comment]
You are correct; my files were still write-locked! Closing issue with this comment. Thanks!!
