### ISSUE TITLE
Methods with arguments are not obfuscated

### ISSUE THREAD

**Issue by hadiidbouk** [rockbruno/swiftshield#30]
Why the method `bla(value: Int)` are not obfuscated here? only the method that doesn't contain argument is being obfuscated

```
class WQGMcFaymSHrKQgsUtEanxlWdnTNPMaZ: UIViewController {

    var WQGMcFaymSHrKQgsUtEanxlWdnTNPMaZ: Int = 0
    var cgjVVuhDZesgqSXcpXJxfBwZoaYJjnDw: String = "Haha"
    
    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    func bla(value: Int) {
        WQGMcFaymSHrKQgsUtEanxlWdnTNPMaZ = value * value
        print(WQGMcFaymSHrKQgsUtEanxlWdnTNPMaZ)
    }
    
    func oyOAsyKRlMdVnLoDcGFEamqksSrjegnq() {
        
    }
}
```

**Comment by rockbruno** [comment]
I avoided obfuscating methods with less than four characters because of a bug where operators like `+` are indexed as regular methods if they are inside a type (`public static func`). Causes nasty issues. They need to be properly indexed as operators for `bla` to be obfuscated. That's the next thing I'll try to fix in Swift

**Comment by hadiidbouk** [comment]
Good to know that, It's better to mention this in the `README`

**Comment by rockbruno** [comment]
It's actually is, linked inside [SOURCEKITISSUES.md](https://github.com/rockbruno/swiftshield/blob/master/SOURCEKITISSUES.md#types-that-wont-be-obfuscated) 🙂
