### ISSUE TITLE
-ignore-modules not work

### ISSUE THREAD

**Issue by MagicalWater** [rockbruno/swiftshield#37]
shell.sh

```
PROJECT_PATH=../RxTestCopy
PROJECT_FILE=RxTest.xcworkspace
IGNORE_LIB=R.swift,R.swift.Library
TARGET=RxTest

chmod -R 774 "${PROJECT_PATH}"

swiftshield -automatic -project-root "${PROJECT_PATH}" -automatic-project-file "${PROJECT_PATH}/${PROJECT_FILE}" -ignore-modules "${IGNORE_LIB}" -automatic-project-scheme "${TARGET}"

```

but R.swift still obfuscated

**Comment by rockbruno** [comment]
Hmm I believe the problem here is the dot, I think Xcode imports that as `R_swift`. If it's easy for you, can you run the obfuscator in verbose mode and tell me how swiftshield detects it? There should be a `Found Module "module name"` after getting the build settings. I'll check it out later anyway.

**Comment by MagicalWater** [comment]
ok, thank you for response, but i was not at computer. i will try it later

**Comment by MagicalWater** [comment]
i try the `R_swift` instead of `R.swift`, but still obfuscated

**Comment by rockbruno** [comment]
Here's how you can debug it if it happen with another library: some pods use different names inside the code.

```
Building project to gather modules and compiler arguments...
Found module Rswift
```

`R.swift.Library` is named `Rswift`. There's no code inside `R.swift` itself, it's just a binary.

**Comment by MagicalWater** [comment]
`Rswift` worked fine, thanks
