### ISSUE TITLE
Storyboard Unwind Segue can no longer be called programmatically

### ISSUE THREAD

**Issue by iosdeveloper** [rockbruno/swiftshield#47]
After running swiftshield, I can no longer use `performSegue()` with the identifier of an unwind segue in storyboard. Any idea how I can debug this?

**Comment by rockbruno** [comment]
Are you using hardcoded strings?

**Comment by iosdeveloper** [comment]
Yes. @rockbruno

**Comment by rockbruno** [comment]
SwiftShield can only obfuscate declarations and references, it unfortunately can't change strings. This is one of the blockers mentioned in the README.md

**Comment by iosdeveloper** [comment]
I'm confused. If it doesn't change it, why would it stop working? I don't see it in README.md either.

**Comment by rockbruno** [comment]
Sorry, I misunderstood the issue. If you open the storyboard, are the connections correct? I don't use storyboards, but if I remember correctly if you have anything connected to File Owner then the connection matches the name of the class with a file with the same name. But since this tool doesn't obfuscate file names, the storyboard would stop working.

**Comment by iosdeveloper** [comment]
Ah, that makes sense now. Thanks.
