### ISSUE TITLE
References to custom class aren't updated in XIB files

### ISSUE THREAD

**Issue by DracoRubi** [rockbruno/swiftshield#61]
Hi. I'm trying to use this tool (a very useful tool, by the way!) for my project. However, I'm running into an issue that I can't solve in my own.

When I use the automatic mode, my custom view classes are obfuscated, but the XIB files where I use said custom view classes aren't refactored with the new names.

For example:
![image](https://user-images.githubusercontent.com/13056881/59620276-be5f0e80-912c-11e9-88be-5c3f0d0b9b33.png)

As you can see, this item has a custom class, PurplePasswortTextField. After obfuscating the code, the PurplePasswortTextField class changes its name to xpduHLOUtQxSXUNtKajuMMLvAcbFICYs, but it isn't modified in the XIB file, which keeps referencing the old PurplePasswortTextField.
That causes the app to crash, because the reference isn't properly set.

I could modify all of those occurrences manually, one by one, but it's a long (and tedious) process. Do you know how to automate this?
I'd appreciate any help or clue that can help me to solve this.
Thanks!

**Comment by rockbruno** [comment]
This was supposed to work, I think the issue might be the `Inherit Module From Target`, as I think I'm specifically looking for the `customModule` parameter inside the xib. If that's the case, then I need to assume that the class belongs to the target of the xib. I can fix this, just give me a moment!

**Comment by rockbruno** [comment]
I would appreciate it if you could send this .xib as well (feel free to hide the names), as we might be dealing with an edge case here

**Comment by rockbruno** [comment]
Can you try the bin here? https://github.com/rockbruno/swiftshield/tree/xibs-without-target
I haven't tested it, but I changed the obfuscation to assume the class's module is the xib's target. It should fix this particular issue (but could bring others... let's see)

**Comment by FredyBellidoT** [comment]
Hi Bruno.
Thanks for the code, but it isn't working. I'm not sure if the issue here is the target, because the custom class is associated to all my targets in the project. The issue is that the references in the XML code of the XIB  file aren't changing.

I'm attaching a screenshot.

![image](https://user-images.githubusercontent.com/25385019/59702379-d9e31b80-91f7-11e9-8bd2-a02e5dcd0503.png)

Thanks a lot for the help!

**Comment by rockbruno** [comment]
I mean what the tool does is check for the obfuscated name based on the `customModule` attribute in your view's xib, but the one you're using doesn't have it because of that option in Xcode.

We might have to rewrite the xib logic entirely for this, so give me some time and I'll address this soon.

**Comment by rockbruno** [comment]
I pushed something to that branch, can you try now?

What's happening here is that your xib has no info on the class's target, but it's really weird because I can't reproduce this. If I create a xib and a class to it, Xcode will always add the `customModule` parameter to it. I edited my xib to strip all this info so it looked like yours (no module info) and the app failed to find the class even without obfuscation. I'm trying to figure out how you ended up with that in first place...
